[meta]
name = "順に打鍵する配列"
keyboard = "jis"

[layers.base.override]
"," = "、"
"." = "。"
"/" = "゜"
0 = "０"
1 = "１"
2 = "２"
3 = "３"
4 = "４"
5 = "５"
6 = "６"
7 = "７"
8 = "８"
9 = "９"
":" = "れ"
";" = "き"
"@" = "ち"
"\\" = "・"
a = "は"
b = "さ"
c = "に"
e = "し"
f = "と"
g = "た"
h = "く"
i = "い"
j = "う"
l = "゛"
m = "る"
n = "っ"
o = "の"
p = "り"
q = "そ"
r = "て"
s = "か"
t = "ょ"
u = "ん"
v = "な"
w = "こ"
x = "け"
y = "つ"
z = "す"

[sequences]
"d,." = "ー"
"d,/" = "ぉ"
"d,:" = "」"
"d,;" = "ゆ"
"d,@" = "「"
"d,a" = "ぃ"
"d,b" = "ゃ"
"d,c" = "せ"
"d,d" = "ら"
"d,e" = "ほ"
"d,f" = "あ"
"d,g" = "よ"
"d,h" = "ま"
"d,i" = "み"
"d,j" = "お"
"d,k" = "も"
"d,l" = "わ"
"d,m" = "ろ"
"d,n" = "む"
"d,o" = "や"
"d,p" = "ぇ"
"d,q" = "ぁ"
"d,r" = "ふ"
"d,s" = "を"
"d,t" = "め"
"d,u" = "え"
"d,v" = "ゅ"
"d,w" = "ひ"
"d,x" = "へ"
"d,y" = "ぬ"
"d,z" = "ぅ"
"k,." = "ー"
"k,/" = "ぉ"
"k,:" = "」"
"k,;" = "ゆ"
"k,@" = "「"
"k,a" = "ぃ"
"k,b" = "ゃ"
"k,c" = "せ"
"k,d" = "ら"
"k,e" = "ほ"
"k,f" = "あ"
"k,g" = "よ"
"k,h" = "ま"
"k,i" = "み"
"k,j" = "お"
"k,k" = "も"
"k,l" = "わ"
"k,m" = "ろ"
"k,n" = "む"
"k,o" = "や"
"k,p" = "ぇ"
"k,q" = "ぁ"
"k,r" = "ふ"
"k,s" = "を"
"k,t" = "め"
"k,u" = "え"
"k,v" = "ゅ"
"k,w" = "ひ"
"k,x" = "へ"
"k,y" = "ぬ"
"k,z" = "ぅ"
