//! DvorakJ scan-code → Key conversion table.

use crate::model::Key;

pub(crate) fn key_from_scancode(code: u32) -> Option<Key> {
    match code {
        0x02 => Some(Key::Num1),
        0x03 => Some(Key::Num2),
        0x04 => Some(Key::Num3),
        0x05 => Some(Key::Num4),
        0x06 => Some(Key::Num5),
        0x07 => Some(Key::Num6),
        0x08 => Some(Key::Num7),
        0x09 => Some(Key::Num8),
        0x0A => Some(Key::Num9),
        0x0B => Some(Key::Num0),
        0x0C => Some(Key::Minus),
        0x0D => Some(Key::Equal),
        0x10 => Some(Key::Q),
        0x11 => Some(Key::W),
        0x12 => Some(Key::E),
        0x13 => Some(Key::R),
        0x14 => Some(Key::T),
        0x15 => Some(Key::Y),
        0x16 => Some(Key::U),
        0x17 => Some(Key::I),
        0x18 => Some(Key::O),
        0x19 => Some(Key::P),
        0x1A => Some(Key::LBracket),
        0x1B => Some(Key::RBracket),
        0x1E => Some(Key::A),
        0x1F => Some(Key::S),
        0x20 => Some(Key::D),
        0x21 => Some(Key::F),
        0x22 => Some(Key::G),
        0x23 => Some(Key::H),
        0x24 => Some(Key::J),
        0x25 => Some(Key::K),
        0x26 => Some(Key::L),
        0x27 => Some(Key::Semicolon),
        0x28 => Some(Key::Quote),
        0x2B => Some(Key::Backslash),
        0x2C => Some(Key::Z),
        0x2D => Some(Key::X),
        0x2E => Some(Key::C),
        0x2F => Some(Key::V),
        0x30 => Some(Key::B),
        0x31 => Some(Key::N),
        0x32 => Some(Key::M),
        0x33 => Some(Key::Comma),
        0x34 => Some(Key::Dot),
        0x35 => Some(Key::Slash),
        0x39 => Some(Key::Space),
        0x73 => Some(Key::Backslash), // JIS "\_" key
        0x7D => Some(Key::Yen),       // JIS "\|" key
        _ => None,
    }
}
